# Generated by Django 5.2 on 2025-04-20 12:04

import django.core.validators
import django.db.models.deletion
import stock.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Max length of this field is 64.', max_length=64, unique=True, verbose_name='Industry name')),
                ('is_defensive', models.BooleanField(verbose_name='Defensive brand')),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Cash'), (2, 'Stock'), (3, 'Bond'), (4, 'Fund')], default=1, help_text='This field is shown in admin page only', verbose_name='Cash info')),
                ('balance', models.PositiveIntegerField(help_text='This value is as of registered time.', verbose_name='Bank account balance')),
                ('registered_date', models.DateTimeField(verbose_name='Registered date')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashes', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('-registered_date',),
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max length of this field is 255.', max_length=255, verbose_name='Title')),
                ('detail', models.JSONField(help_text='Relevant asset list as of created time (json format).', verbose_name='Relevant assets')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Cash'), (2, 'Stock'), (3, 'Bond'), (4, 'Fund')], default=2, help_text='This field is shown in admin page only', verbose_name='Stock info')),
                ('code', models.CharField(help_text='This field consists of either only numbers or both alphabets and numbers.', max_length=16, unique=True, validators=[stock.models._validate_code], verbose_name='Stock code')),
                ('name', models.CharField(help_text='Max length of this field is 255.', max_length=255, verbose_name='Stock name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock price')),
                ('dividend', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dividend')),
                ('per', models.DecimalField(blank=True, decimal_places=2, help_text='Price Earnings Ratio', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PER')),
                ('pbr', models.DecimalField(blank=True, decimal_places=2, help_text='Price Book-value Ratio', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PBR')),
                ('eps', models.DecimalField(blank=True, decimal_places=2, help_text='Earnings Per Share', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='EPS')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.industry', verbose_name='Stock industry')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PurchasedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name='Purchased date')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='The number of purchased stocks')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_stocks', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('stock', models.ForeignKey(help_text='This field is shown in admin page only', on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='Target stock')),
            ],
            options={
                'ordering': ('-purchase_date', 'stock__code'),
            },
        ),
    ]
