# Generated by Django 5.2 on 2025-04-21 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_purchasedstock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedstock',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='The number of purchased stocks'),
        ),
    ]
