# Generated by Django 5.2 on 2025-04-23 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_purchasedstock_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='price_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='dividend_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='per_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='pbr_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='eps_gte_0',
        ),
        migrations.AddConstraint(
            model_name='purchasedstock',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0_in_purchased_stock'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0_in_stock'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('dividend__gte', 0)), name='dividend_gte_0_in_stock'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('per__gte', 0)), name='per_gte_0_in_stock'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('pbr__gte', 0)), name='pbr_gte_0_in_stock'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('eps__gte', 0)), name='eps_gte_0_in_stock'),
        ),
    ]
