# Generated by Django 5.2 on 2025-05-01 16:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_stock_price_gte_0_remove_stock_dividend_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='purchasedstock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average trade price'),
        ),
    ]
