# Generated by Django 5.2 on 2025-05-02 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_snapshot_uuid_alter_purchasedstock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 2, 8, 39, 3, 287926, tzinfo=datetime.timezone.utc), verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 2, 8, 39, 9, 68540, tzinfo=datetime.timezone.utc), verbose_name='Start date'),
            preserve_default=False,
        ),
    ]
