# Generated by Django 5.2 on 2025-05-02 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_snapshot_end_date_snapshot_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date'),
        ),
    ]
