# Generated by Django 5.2.1 on 2025-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_stock_eps_gte_0_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='skip_task',
            field=models.BooleanField(default=False, verbose_name='Skip executing user task'),
        ),
    ]
