# Generated by Django 5.2 on 2025-04-20 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='detail',
            field=models.JSONField(blank=True, help_text='Relevant asset list as of created time (json format).', verbose_name='Relevant assets'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dividend'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.industry', verbose_name='Stock industry'),
        ),
    ]
