# Generated by Django 5.2 on 2025-04-21 15:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_cash_category_remove_stock_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedstock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trade price'),
        ),
        migrations.AlterField(
            model_name='purchasedstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='Target stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Dividend'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='eps',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Earnings Per Share', max_digits=7, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pbr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price Book-value Ratio', max_digits=7, verbose_name='PBR'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='per',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price Earnings Ratio', max_digits=7, verbose_name='PER'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock price'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('dividend__gte', 0)), name='dividend_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('per__gte', 0)), name='per_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('pbr__gte', 0)), name='pbr_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('eps__gte', 0)), name='eps_gte_0'),
        ),
    ]
