# Generated by Django 5.2 on 2025-04-21 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_purchasedstock_price_alter_purchasedstock_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedstock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trade price'),
        ),
    ]
