# Generated by Django 5.2.1 on 2025-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_snapshot_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='bps',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Book value Per Share', max_digits=7, verbose_name='BPS'),
        ),
        migrations.AddField(
            model_name='stock',
            name='er',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Equity Ratio', max_digits=5, verbose_name='ER'),
        ),
        migrations.AddField(
            model_name='stock',
            name='roe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Return On Equity', max_digits=6, verbose_name='ROE'),
        ),
    ]
