# Generated by Django 5.2.1 on 2025-05-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_stock_bps_stock_er_stock_roe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='eps_gte_0_in_stock',
        ),
    ]
