# Generated by Django 5.2.2 on 2025-09-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_stock_skip_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedstock',
            name='has_been_sold',
            field=models.BooleanField(default=False, verbose_name='Its stock has been sold or not'),
        ),
    ]
