# Generated by Django 5.2.2 on 2025-09-07 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_purchasedstock_has_been_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ('priority', '-created_at')},
        ),
        migrations.AddField(
            model_name='snapshot',
            name='priority',
            field=models.IntegerField(default=99, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Priority to show the snapshot'),
        ),
    ]
