# Generated by Django 5.2.9 on 2025-12-27 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_snapshot_options_snapshot_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.CreateModel(
            name='LocalizedIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], max_length=10, verbose_name='Language code')),
                ('name', models.CharField(help_text='Max length of this field is 64.', max_length=64, verbose_name='Industry name')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locals', to='stock.industry', verbose_name='Localized industry')),
            ],
            options={
                'unique_together': {('industry', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='LocalizedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], max_length=10, verbose_name='Language code')),
                ('name', models.CharField(help_text='Max length of this field is 64.', max_length=64, verbose_name='Industry name')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locals', to='stock.stock', verbose_name='Localized stock')),
            ],
            options={
                'unique_together': {('stock', 'language_code')},
            },
        ),
    ]
