# Generated by Django 5.2.9 on 2025-12-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_remove_industry_name_remove_stock_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizedindustry',
            name='name',
            field=models.CharField(help_text='Max length of this field is 64.', max_length=64, verbose_name='Localized name'),
        ),
        migrations.AlterField(
            model_name='localizedstock',
            name='name',
            field=models.CharField(help_text='Max length of this field is 64.', max_length=64, verbose_name='Localized name'),
        ),
    ]
