# Generated by Django 5.2.9 on 2026-02-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_localizedindustry_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ('priority', '-end_date')},
        ),
    ]
