# Generated by Django 5.2.9 on 2026-04-24 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_snapshot_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockScreener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max length of this field is 255.', max_length=255, verbose_name='Title')),
                ('criteria', models.TextField(help_text='Criteria to screen stocks.', verbose_name='Criteria')),
                ('ordering', models.TextField(help_text='Ordering type of stocks.', verbose_name='Ordering')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
