# Generated by Django 5.2.9 on 2026-04-24 19:11

import stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_stockscreener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockscreener',
            name='criteria',
            field=models.TextField(help_text='Criteria to screen stocks.', validators=[stock.models.stock_validator], verbose_name='Criteria'),
        ),
        migrations.AlterField(
            model_name='stockscreener',
            name='ordering',
            field=models.TextField(help_text='Ordering type of stocks.', validators=[stock.models.stock_ordering_validator], verbose_name='Ordering'),
        ),
    ]
