# Generated by Django 5.2.9 on 2026-04-25 09:13

import stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_alter_stockscreener_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockscreener',
            name='ordering',
            field=models.TextField(blank=True, help_text='Ordering type of stocks.', validators=[stock.models.stock_ordering_validator], verbose_name='Ordering'),
        ),
    ]
