# Generated by Django 5.2.9 on 2026-04-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_alter_stockscreener_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockscreener',
            options={'ordering': ('pk',)},
        ),
    ]
