# Generated by Django 5.2.9 on 2026-04-25 13:03

import django.core.validators
import django.db.models.deletion
import stock.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_stockscreener_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockscreener',
            options={'ordering': ('-priority',)},
        ),
        migrations.RemoveField(
            model_name='stockscreener',
            name='criteria',
        ),
        migrations.AddField(
            model_name='stockscreener',
            name='condition',
            field=models.TextField(default='', help_text='Condition to screen stocks.', validators=[stock.models.stock_validator], verbose_name='Condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockscreener',
            name='priority',
            field=models.IntegerField(default=99, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Priority to show the stock screener'),
        ),
        migrations.AlterField(
            model_name='stockscreener',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
