# Generated by Django 5.2.9 on 2026-04-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_stockscreener_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockscreener',
            options={'ordering': ('priority', 'title')},
        ),
    ]
