# Generated by Django 5.2.9 on 2026-04-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_alter_stockscreener_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit: 100 million yen', max_digits=10, verbose_name='Market Capitalization'),
        ),
        migrations.AddField(
            model_name='stock',
            name='operating_cashflow',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit: 100 million yen', max_digits=10, verbose_name='Operating Cashflow'),
        ),
        migrations.AddField(
            model_name='stock',
            name='payout_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Payout Ratio'),
        ),
    ]
