# Generated by Django 5.2.9 on 2026-04-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_stock_market_cap_stock_operating_cashflow_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('market_cap__gte', 0)), name='marketcap_gte_0_in_stock'),
        ),
    ]
